name: Pull Request Workflow
on: [pull_request]

jobs:
  Pytest_Coveralls:
    runs-on: ubuntu-18.04
    env:
      CGBEACON2_CONFIG: ../instance/config.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install required linux libs
      run: |
        sudo apt-get install curl libcurl4 libcurl4-openssl-dev gcc bedtools
    - name: Install repo and its dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .
        pip install pytest
        pip install coveralls
    - name: Run pytest and coveralls
      run: |
        pytest --cov=cgbeacon2 tests/
        coveralls
      env:
        GITHUB_TOKEN: ${{ github.token }}

  wemake-styleguide:
    runs-on: ubuntu-18.04
    steps:
      - name: Install required linux libs
        run: |
          sudo apt-get install git-all
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.14.1
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
