name: Pull Request Workflow
on: [pull_request]

jobs:
  Pytest_Coveralls:
    runs-on: ubuntu-18.04
    env:
      CGBEACON2_CONFIG: ../instance/config.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install required linux libs
      run: |
        sudo apt-get install curl libcurl4 libcurl4-openssl-dev gcc bedtools
    - name: Install repo and its dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .
        pip install pytest
        pip install coveralls
    - name: Run pytest and coveralls
      run: |
        pytest --cov=cgbeacon2 tests/
        coveralls
      env:
        GITHUB_TOKEN: ${{ github.token }}

  flake8:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
