name: Python Pull Request Workflow
on: [pull_request]
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    env:
      CGBEACON2_CONFIG: ../instance/config.py
    steps:
      - uses: actions/checkout@v2
      - name: Install missing linux libraries
        run: |
          sudo apt-get install curl libcurl4 libcurl4-openssl-dev gcc bedtools
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pytest
          pytest
